import React, { useState, useEffect } from 'react';
import jobsData from '../data/jobs.json';

const Digest = () => {
    const [preferences, setPreferences] = useState(null);
    const [digest, setDigest] = useState(null);
    const [generatedDate, setGeneratedDate] = useState(null);
    const [toast, setToast] = useState(null);

    useEffect(() => {
        // Load Preferences
        const prefs = JSON.parse(localStorage.getItem('jobTrackerPreferences'));
        setPreferences(prefs);

        // Check for existing digest for today
        const today = new Date().toISOString().split('T')[0];
        const savedDigest = localStorage.getItem(`jobTrackerDigest_${today}`);

        if (savedDigest) {
            setDigest(JSON.parse(savedDigest));
            setGeneratedDate(today);
        }
    }, []);

    const calculateMatchScore = (job, prefs) => {
        let score = 0;
        if (!prefs) return 0;

        // 1. Role Keyword Match (+25 Title, +15 Description)
        const keywords = prefs.roleKeywords.toLowerCase().split(',').map(k => k.trim()).filter(k => k);
        let titleMatch = false;
        let descMatch = false;

        keywords.forEach(keyword => {
            if (job.title.toLowerCase().includes(keyword)) titleMatch = true;
            if (job.description.toLowerCase().includes(keyword)) descMatch = true;
        });

        if (titleMatch) score += 25;
        if (descMatch) score += 15;

        // 2. Location Match (+15)
        const prefLocs = prefs.preferredLocations.toLowerCase().split(',').map(l => l.trim()).filter(l => l);
        let locMatch = false;
        prefLocs.forEach(loc => {
            if (job.location.toLowerCase().includes(loc)) locMatch = true;
        });
        if (locMatch) score += 15;

        // 3. Mode Match (+10)
        if (prefs.preferredMode && prefs.preferredMode[job.mode]) {
            score += 10;
        }

        // 4. Experience Match (+10)
        if (prefs.experienceLevel.includes(job.experience)) {
            score += 10;
        }

        // 5. Skills Overlap (+15)
        const userSkills = prefs.skills.toLowerCase().split(',').map(s => s.trim()).filter(s => s);
        const jobSkills = job.skills.map(s => s.toLowerCase());
        const skillOverlap = userSkills.some(us => jobSkills.includes(us));
        if (skillOverlap) score += 15;

        // 6. Recency (+5)
        if (job.postedDaysAgo <= 2) score += 5;

        // 7. Source (+5)
        if (job.source === 'LinkedIn') score += 5;

        return Math.min(score, 100);
    };

    const generateDigest = () => {
        if (!preferences) return;

        const today = new Date().toISOString().split('T')[0];

        // 1. Score all jobs
        const scoredJobs = jobsData.map(job => ({
            ...job,
            matchScore: calculateMatchScore(job, preferences)
        }));

        // 2. Filter & Sort (Match Score DESC, then Date Posted ASC)
        // Taking top 10 matches > 0 score
        const topJobs = scoredJobs
            .filter(job => job.matchScore > 0)
            .sort((a, b) => {
                if (b.matchScore !== a.matchScore) return b.matchScore - a.matchScore;
                return a.postedDaysAgo - b.postedDaysAgo;
            })
            .slice(0, 10);

        setDigest(topJobs);
        setGeneratedDate(today);
        localStorage.setItem(`jobTrackerDigest_${today}`, JSON.stringify(topJobs));
    };

    const getDigestText = () => {
        if (!digest) return '';
        let text = `My 9AM Job Digest - ${generatedDate}\n\n`;
        digest.forEach((job, index) => {
            text += `${index + 1}. ${job.title} at ${job.company}\n`;
            text += `   Match: ${job.matchScore}% | Location: ${job.location}\n`;
            text += `   Apply: ${job.applyUrl}\n\n`;
        });
        text += "Generated by KodNest Job Tracker.";
        return text;
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(getDigestText());
        setToast('Digest copied to clipboard!');
        setTimeout(() => setToast(null), 3000);
    };

    const handleEmail = () => {
        const subject = `My 9AM Job Digest - ${generatedDate}`;
        const body = encodeURIComponent(getDigestText());
        window.location.href = `mailto:?subject=${subject}&body=${body}`;
    };

    return (
        <div className="container" style={{ padding: 'var(--spacing-5) var(--spacing-3)', maxWidth: '800px' }}>
            {toast && (
                <div style={{
                    position: 'fixed', top: '80px', right: '20px',
                    backgroundColor: 'var(--color-success)', color: 'white',
                    padding: '12px 24px', borderRadius: '4px',
                    boxShadow: '0 2px 4px rgba(0,0,0,0.1)', zIndex: 1000,
                    animation: 'fadeIn 0.3s'
                }}>
                    {toast}
                </div>
            )}

            {!preferences ? (
                <div style={{ textAlign: 'center', marginTop: '60px', color: 'var(--color-text-secondary)' }}>
                    <h3 style={{ fontFamily: 'var(--font-serif)', fontSize: '24px', marginBottom: '16px' }}>
                        Personalize Your Digest.
                    </h3>
                    <p style={{ fontSize: '18px', marginBottom: '24px' }}>Set your preferences to generate a personalized job digest.</p>
                    <a href="/settings" className="btn btn-primary">Go to Settings</a>
                </div>
            ) : !digest ? (
                <div style={{ textAlign: 'center', marginTop: '40px' }}>
                    <h1 style={{
                        fontFamily: 'var(--font-serif)',
                        fontSize: 'var(--text-3xl)',
                        letterSpacing: '-1px',
                        marginBottom: 'var(--spacing-3)'
                    }}>
                        Daily Brief.
                    </h1>
                    <p style={{
                        fontSize: 'var(--text-lg)',
                        color: 'var(--color-text-secondary)',
                        marginBottom: '32px'
                    }}>
                        Your personalized top 10 job matches are ready.
                    </p>
                    <button onClick={generateDigest} className="btn btn-primary" style={{ padding: '12px 24px', fontSize: '16px' }}>
                        Generate Today's 9AM Digest (Simulated)
                    </button>
                    <p style={{ fontSize: '12px', color: '#999', marginTop: '16px' }}>
                        * Demo Mode: Daily 9AM trigger simulated manually.
                    </p>
                </div>
            ) : (
                <>
                    <div style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        marginBottom: '24px',
                        flexWrap: 'wrap',
                        gap: '16px'
                    }}>
                        <h1 style={{
                            fontFamily: 'var(--font-serif)',
                            fontSize: '28px',
                            letterSpacing: '-1px',
                            margin: 0
                        }}>
                            Today's Digest
                        </h1>
                        <div style={{ display: 'flex', gap: '12px' }}>
                            <button onClick={handleCopy} className="btn btn-secondary" style={{ fontSize: '13px' }}>
                                Copy Text
                            </button>
                            <button onClick={handleEmail} className="btn btn-secondary" style={{ fontSize: '13px' }}>
                                Email Draft
                            </button>
                        </div>
                    </div>

                    {/* Email Style Container */}
                    <div style={{
                        backgroundColor: 'white',
                        border: '1px solid #e0e0e0',
                        borderRadius: '8px',
                        padding: '40px',
                        boxShadow: '0 2px 8px rgba(0,0,0,0.05)'
                    }}>
                        <div style={{ borderBottom: '1px solid #eee', paddingBottom: '24px', marginBottom: '24px' }}>
                            <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '24px', marginBottom: '8px', color: '#333' }}>
                                Top 10 Jobs For You
                            </h2>
                            <p style={{ color: '#666', fontSize: '14px' }}>
                                {new Date(generatedDate).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                            </p>
                        </div>

                        {digest.length === 0 ? (
                            <div style={{ textAlign: 'center', padding: '40px', color: '#999' }}>
                                <p>No matching roles found today based on your preferences.</p>
                                <p>Try adjusting your criteria in Settings.</p>
                            </div>
                        ) : (
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
                                {digest.map((job, index) => (
                                    <div key={job.id} style={{
                                        display: 'flex',
                                        justifyContent: 'space-between',
                                        alignItems: 'flex-start',
                                        paddingBottom: '24px',
                                        borderBottom: index < digest.length - 1 ? '1px solid #f5f5f5' : 'none'
                                    }}>
                                        <div>
                                            <h3 style={{ fontSize: '18px', fontWeight: 600, color: 'var(--color-primary)', marginBottom: '4px' }}>
                                                {job.title}
                                            </h3>
                                            <p style={{ fontSize: '14px', color: '#555', marginBottom: '4px' }}>
                                                {job.company} • {job.location}
                                            </p>
                                            <div style={{ display: 'flex', gap: '12px', fontSize: '12px', color: '#888' }}>
                                                <span>{job.experience} Yrs</span>
                                                <span style={{ color: 'var(--color-success)', fontWeight: 600 }}>{job.matchScore}% Match</span>
                                            </div>
                                        </div>
                                        <a href={job.applyUrl} target="_blank" rel="noopener noreferrer"
                                            className="btn btn-primary"
                                            style={{ padding: '6px 16px', fontSize: '12px', textDecoration: 'none' }}>
                                            Apply
                                        </a>
                                    </div>
                                ))}
                            </div>
                        )}

                        <div style={{
                            marginTop: '40px',
                            paddingTop: '24px',
                            borderTop: '1px solid #eee',
                            textAlign: 'center',
                            fontSize: '12px',
                            color: '#999'
                        }}>
                            This digest was generated based on your preferences.
                        </div>
                    </div>

                    {/* Status Updates Section */}
                    <div style={{ marginTop: '40px' }}>
                        <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '24px', marginBottom: '16px' }}>
                            Recent Status Updates
                        </h2>
                        {(() => {
                            const history = JSON.parse(localStorage.getItem('jobTrackerStatusHistory')) || [];
                            if (history.length === 0) {
                                return <p style={{ color: '#999' }}>No recent status updates.</p>;
                            }
                            return (
                                <div style={{ backgroundColor: 'white', borderRadius: '8px', border: '1px solid #e0e0e0', padding: '0 24px' }}>
                                    {history.map((item, index) => {
                                        const job = jobsData.find(j => j.id === item.jobId);
                                        if (!job) return null;
                                        return (
                                            <div key={index} style={{
                                                padding: '16px 0',
                                                borderBottom: index < history.length - 1 ? '1px solid #f5f5f5' : 'none',
                                                display: 'flex', justifyContent: 'space-between', alignItems: 'center'
                                            }}>
                                                <div>
                                                    <div style={{ fontWeight: 600, fontSize: '15px' }}>{job.title}</div>
                                                    <div style={{ fontSize: '13px', color: '#666' }}>{job.company}</div>
                                                </div>
                                                <div style={{ textAlign: 'right' }}>
                                                    <span style={{
                                                        fontSize: '12px', padding: '4px 8px', borderRadius: '4px', fontWeight: 500,
                                                        backgroundColor: item.status === 'Applied' ? '#E3F2FD' :
                                                            item.status === 'Rejected' ? '#FFEBEE' :
                                                                item.status === 'Selected' ? '#E8F5E9' : '#F5F5F5',
                                                        color: item.status === 'Applied' ? '#1976D2' :
                                                            item.status === 'Rejected' ? '#D32F2F' :
                                                                item.status === 'Selected' ? '#388E3C' : '#666'
                                                    }}>
                                                        {item.status}
                                                    </span>
                                                    <div style={{ fontSize: '11px', color: '#999', marginTop: '4px' }}>
                                                        {new Date(item.date).toLocaleDateString()}
                                                    </div>
                                                </div>
                                            </div>
                                        );
                                    })}
                                </div>
                            );
                        })()}
                    </div>
                </>
            )}
        </div>
    );
};

export default Digest;
